language: csharp
sudo: false  # use the new container-based infrastructure
cache: apt
install: curl -sSL https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh | sh && source ~/.kre/kvm/kvm.sh && kvm upgrade
script:
  - . ./build.sh
